apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 116981799763.dkr.ecr.ap-south-1.amazonaws.com/b12:19ad7de4fdb693ea43ff2d239ef6da63cff9c846
          ports:
            - containerPort: 3000
